Repository AY2425S2-CS2103-F08-3/tp, pull requests merged in 2025-03, with the labels that each got.

#9 Add Xiao Yong's photo
  docs/images/caxewhy.png
Labels: type.Task

#17 Add Lester's Photo
  docs/images/lesterlimjj.png
Labels: type.Task

#22 Add Lemuel's Photo
  docs/images/ryuse.png
Labels: type.Task

#26 Add Jian Cheng's Photo
  docs/images/jiancheng37.png
Labels: type.Task

#28 Update About Us page with Jian Cheng's details
  docs/AboutUs.md
  docs/team/jiancheng.md
  docs/team/johndoe.md
Labels: type.Task

#15 Update AboutUs page with Zhao Yi's details
  docs/AboutUs.md
  docs/team/jiancheng.md
  docs/team/xiaoyong.md
  docs/team/zhaoyi.md
Labels: type.Task

#19 Update AboutUs page with Lester's details
  docs/AboutUs.md
  docs/team/lester.md
Labels: type.Task

#21 Update About Us page with Lemuel's details
  docs/AboutUs.md
  docs/team/jiancheng.md
  docs/team/lester.md
  docs/team/ryuse.md
  docs/team/xiaoyong.md
  docs/team/zhaoyi.md
Labels: type.Task

#30 Update readme.md
  README.md
  docs/images/Ui.png
Labels: type.Task

#42 Update use cases in developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#40 Update Glossary in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#38 Update NFRs in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#33 Add value proposition to developer's guide
  docs/DeveloperGuide.md
Labels: type.Task

#44 Update Value Proposition in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#45 Update user stories in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#47 Fix use case extension numbering in developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#56 Add price class for future Listing model
  src/main/java/seedu/address/model/price/Price.java
Labels: type.Task, priority.High

#63 Remove address from Person model
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#64 Remove tags from Person model
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#58 Add postal code field class for future Listing model
  src/main/java/seedu/address/model/listing/PostalCode.java
Labels: type.Task, priority.High

#59 Add house number field class for future Listing model
  src/main/java/seedu/address/model/listing/HouseNumber.java
Labels: type.Task, priority.High

#60 Add unit number field class for future Listing model
  src/main/java/seedu/address/model/listing/UnitNumber.java
Labels: type.Task, priority.High

#61 Add property name field class for future Listing model
  src/main/java/seedu/address/model/listing/PropertyName.java
Labels: type.Task, priority.High

#57 Add priceRange class for future Listing model
  src/main/java/seedu/address/model/price/PriceRange.java
Labels: type.Task, priority.High

#67 Add listing class
  src/main/java/seedu/address/model/listing/Listing.java
Labels: type.Task, priority.High

#71 Add tag registry
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagRegistry.java
  src/main/java/seedu/address/model/tag/exceptions/DuplicateTagException.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
Labels: type.Task, priority.High

#70 Add unique listing list
  src/main/java/seedu/address/model/listing/UniqueListingList.java
  src/main/java/seedu/address/model/listing/exceptions/DuplicateListingException.java
  src/main/java/seedu/address/model/listing/exceptions/ListingNotFoundException.java
Labels: type.Task, priority.High

#72 Rename add command to addPerson command
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#77 Update Command Response UI
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#76 Update Person listing UI
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Task

#80 Add addListingCommand
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Task, priority.High

#82 Add Property Preference class
  src/main/java/seedu/address/model/person/PropertyPreference.java
Labels: priority.High

#85 Modify find command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Task, priority.High

#91 Add property list command
  src/main/java/seedu/address/logic/commands/ListListingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
Labels: type.Task, priority.High

#92 Add person list command
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#96 Add tag list UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TagListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TagListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Task, priority.High

#98 Add tag command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task, priority.High

#99 Add tags to property preferences, and vice versa
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagRegistry.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/tag/TagRegistryTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Task, priority.High

#102 Add list tag command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/TagListPanel.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Task, priority.High

#110 Edit person command
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#111 Add property preferences UI branch
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PreferenceListCard.java
  src/main/java/seedu/address/ui/PreferenceListPanel.java
  src/main/resources/view/PreferenceListCard.fxml
  src/main/resources/view/PreferenceListPanel.fxml
Labels: type.Task, priority.High

#118 Update command list in help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.High

#119 Remove associations from equals function
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug, priority.High

#116 Shift command bar to above tag list
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Task, priority.High

#124 Add delete person command
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Task, priority.High

#122 Add persistent storage
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPreference.java
  src/main/java/seedu/address/storage/JsonAdaptedPriceRange.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task, priority.High

#125 Add property preference command
  src/main/java/seedu/address/logic/parser/AddPreferenceCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.High

#134 Add association to Person for Property Preferences
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/parser/AddPreferenceCommandParser.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
Labels: type.Task, priority.High

#135 Add deleteOwner command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteOwnerCommandParser.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Story, priority.High

#149 Fix storage of listing with no property name
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
Labels: type.Bug, priority.High

#148 Add tag counter in UI
  src/main/java/seedu/address/ui/TagListPanel.java
Labels: type.Enhancement, priority.High

#145 Fix tags association upon initialization
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Bug, priority.High, severity.High

#139 Remove preference constructor
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPreference.java
  src/test/java/seedu/address/model/tag/TagRegistryTest.java
Labels: type.Task, priority.High

#151 Fix model equal function to not contain associations
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug, priority.High, severity.Low

#155 Fix delete property preference not updating tag counter properly
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
Labels: type.Bug, help wanted, priority.High, severity.High

#158 Disable editPerson and clear commands
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High, severity.High

#159 Remove immutability from associations in models
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Task, priority.High, severity.High

#144 Add delete tag command
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Story, priority.High

#163 Able to assign same Person as Listing owner multiple times
  src/main/java/seedu/address/logic/commands/AssignListingCommand.java
Labels: type.Bug, type.Task, priority.High

#164 Update storage initialization with new mutable models
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPreference.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Task, priority.High

#141 Add delete tag from property command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePropertyTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePropertyTagCommandTest.java
  src/test/java/seedu/address/logic/parser/DeletePropertyTagCommandParserTest.java
Labels: type.Story, priority.High

#168 Update clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.High

#170 Rename findCommand to findPersonCommand
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java
Labels: type.Task, priority.High

#174 Rename deleteCommand to deletePersonCommand
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
Labels: type.Task, priority.High

#173 Add delete preference tag command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java
Labels: type.Story, priority.High

#167 Add delete property command
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteListingCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Story, priority.High

#176 Add add preference tag command
  src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
  src/main/java/seedu/address/logic/parser/AddPreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Story, priority.High

#180 Fix bug where no exception thrown when 1 index is provided for command where 2 indices is required
  src/main/java/seedu/address/logic/parser/AddPreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignListingCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteOwnerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
Labels: type.Bug, priority.High

#182 Property preference cannot be created without tags
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/parser/AddPreferenceCommandParser.java
Labels: type.Bug, priority.High

#183 Update UI padding, margins, colors, etc.
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TagListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PreferenceListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TagListPanel.fxml
Labels: type.Task, priority.High

#184 Update help command
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#188 Standardize javadocs
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/AssignListingCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPreferenceCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignListingCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteListingCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteOwnerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
Labels: type.Task, priority.Medium

#190 Update messages for commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/AssignListingCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPreferenceCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignListingCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteListingCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteOwnerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePropertyTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePropertyTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
Labels: type.Task, priority.High

#195 Add overwrite tags to property preference command
  src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/OverwritePreferenceTagCommandParser.java
Labels: type.Story, priority.High

#193 Add project website changes
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Task, priority.High

#198 Add overwrite tags to property command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePropertyTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/OverwritePropertyTagCommandParser.java
Labels: type.Story, priority.High

#200 Search property by tags
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SearchPropertyByTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchPropertyByTagCommandParser.java
  src/main/java/seedu/address/model/listing/predicates/ListingContainsAllTagsPredicate.java
  src/test/java/seedu/address/logic/commands/SearchPropertyByTagCommandTest.java
  src/test/java/seedu/address/model/listing/predicates/ListingContainsAllTagsPredicateTest.java
Labels: type.Story, priority.High

#211 Update edit person command mutability
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
Labels: type.Story, priority.Medium

#208 Mark a property as available
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
  src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
  src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkAvailableCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkUnavailableCommandParser.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/resources/view/ListingListCard.fxml
  src/test/java/seedu/address/logic/commands/DeletePropertyTagCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchPropertyByTagCommandTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/model/listing/predicates/ListingContainsAllTagsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagRegistryTest.java
Labels: type.Story, priority.Medium

#212 Add matchPerson command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyTagCommand.java
  src/main/java/seedu/address/logic/commands/ListListingCommand.java
  src/main/java/seedu/address/logic/commands/MatchPersonCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePropertyTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MatchPersonCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/model/price/PriceRange.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Story, priority.Medium

#217 Add searchSellerProperty command
  src/main/java/seedu/address/logic/commands/AssignListingCommand.java
  src/main/java/seedu/address/logic/commands/SearchOwnerPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchOwnerPropertyCommandParser.java
  src/main/java/seedu/address/model/listing/predicates/ListingContainsOwnerPredicate.java
Labels: type.Story, priority.Medium

#203 Search persons by tags
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchPersonByTagCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/model/person/predicates/PersonPropertyPreferencesContainAllTagsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchPersonByTagCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchPersonByTagCommandParserTest.java
  src/test/java/seedu/address/model/person/predicates/PersonPropertyPreferencesContainAllTagsPredicateTest.java
Labels: type.Story, priority.Medium

#215 Add matchProperty command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/MatchListingCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MatchListingCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Story, priority.Medium

#209 Fix commands not responding to missing prefixes and arguments
  src/main/java/seedu/address/logic/commands/DeletePropertyTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchPropertyByTagCommand.java
  src/main/java/seedu/address/logic/parser/DeletePropertyTagCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchPropertyByTagCommandParser.java
  src/test/java/seedu/address/logic/commands/DeletePropertyTagCommandTest.java
  src/test/java/seedu/address/logic/parser/DeletePropertyTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchPropertyByTagCommandParserTest.java
Labels: type.Task, priority.High

#228 Update model component developer guide
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/BetterTagAttributesClassDiagram.puml
  docs/diagrams/ListingAttributesClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonAttributesClassDiagram.puml
  docs/diagrams/PriceRangeAttributesClassDiagram.puml
  docs/team/ryuse.md
Labels: type.Task, priority.High

#222 Update delete Person sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/DeletePersonSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task, priority.High

#229 Fix UI resetting person list after every command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/AssignListingCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/DeletePropertyTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListListingCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListTagCommand.java
  src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
  src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
  src/main/java/seedu/address/logic/commands/MatchListingCommand.java
  src/main/java/seedu/address/logic/commands/MatchPersonCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePropertyTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchPropertyByTagCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/listing/comparators/ListingPreferenceScoreComparator.java
  src/main/java/seedu/address/model/listing/predicates/ListingMatchesPreferencePredicate.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/model/person/comparators/PersonListingScoreComparator.java
  src/main/java/seedu/address/model/person/predicates/PersonMatchesPropertyPredicate.java
  src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAllActiveSearchTagsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PropertyPreferencesContainAnyActiveSearchTagsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchPropertyByTagCommandTest.java
Labels: type.Bug, priority.High

#219 Add proposed editTag command sequence diagram in DG
  docs/DeveloperGuide.md
  docs/diagrams/EditTagSequenceDiagram.puml
Labels: type.Task, priority.High

#225 Highlight tags and price UI for match commands
  src/main/java/seedu/address/logic/commands/ListListingCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListTagCommand.java
  src/main/java/seedu/address/logic/commands/MatchListingCommand.java
  src/main/java/seedu/address/logic/commands/MatchPersonCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchPropertyByTagCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/price/PriceRange.java
  src/main/java/seedu/address/model/tag/TagRegistry.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PreferenceListCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/DeletePropertyTagCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchPropertyByTagCommandTest.java
Labels: type.Task, priority.Medium

#234 Enable assertions in build.gradle
  build.gradle
Labels: type.Task, priority.High

#232 Update storage component developer guide
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task, priority.High

#236 Add proposed editListing sequence diagram in DG
  docs/DeveloperGuide.md
  docs/diagrams/EditListingSequenceDiagram.puml
Labels: type.Task, priority.High

#240 Update help command with new v1.4 commands
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#244 Fix matchPerson and matchProperty predicates
  src/main/java/seedu/address/model/listing/predicates/ListingMatchesPreferencePredicate.java
  src/main/java/seedu/address/model/person/predicates/PersonMatchesPropertyPredicate.java
Labels: type.Bug, priority.High, alpha-bug

#253 Rename assignListing to addOwner
  src/main/java/seedu/address/logic/commands/AddOwnerCommand.java
  src/main/java/seedu/address/logic/parser/AddOwnerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.Medium

#242 Update UI CD
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/ui/PreferenceCard.java
  src/main/java/seedu/address/ui/PreferenceListPanel.java
Labels: type.Task, priority.High

#251 Rename use of Property to Listing in command
  src/main/java/seedu/address/logic/commands/DeleteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/MatchListingCommand.java
  src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchListingByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchOwnerListingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/OverwriteListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchListingByTagCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchOwnerListingCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchOwnerPropertyCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/DeleteListingTagCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchListingByTagCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteListingTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchListingByTagCommandParserTest.java
Labels: type.Task, priority.Medium

#246 Fix Tags and Price Range unintended highlightings in UI
  src/main/java/seedu/address/logic/commands/MatchListingCommand.java
  src/main/java/seedu/address/logic/commands/MatchPersonCommand.java
  src/main/java/seedu/address/logic/commands/SearchListingByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchOwnerListingCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SearchType.java
  src/main/java/seedu/address/model/listing/predicates/ListingMatchesPreferencePredicate.java
  src/main/java/seedu/address/model/person/predicates/PersonMatchesPropertyPredicate.java
  src/main/java/seedu/address/model/price/PriceRange.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/java/seedu/address/ui/PreferenceCard.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
Labels: type.Bug, priority.High

#248 Convert tagRegistry to a list model
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchListingByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/tag/UniqueTagMap.java
  src/main/java/seedu/address/storage/JsonAdaptedListing.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPreference.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteListingTagCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchListingByTagCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/tag/UniqueTagMapTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task, priority.Medium

#258 Update Storage DG description
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#305 Fix Main Window size being too small
  src/main/java/seedu/address/commons/core/GuiSettings.java
Labels: type.Bug, severity.Low, alpha-bug

#263 Rename findPerson to searchPersonByName
  src/main/java/seedu/address/logic/commands/SearchListingByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByName.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchPersonByNameParser.java
  src/main/java/seedu/address/model/listing/predicates/ListingMatchesPreferencePredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/SearchPersonByNameTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchPersonByNameParserTest.java
Labels: type.Task, priority.Medium

#307 Fix help window focus when minimized
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.Medium, severity.Low

#309 Fix App Name and Icon
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/match_estate.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#311 Fix price to handle large values
  src/main/java/seedu/address/logic/parser/MarkAvailableCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkUnavailableCommandParser.java
  src/main/java/seedu/address/logic/parser/MatchListingCommandParser.java
  src/main/java/seedu/address/logic/parser/MatchPersonCommandParser.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/storage/JsonAdaptedPriceRange.java
Labels: type.Bug, severity.High

#264 Adding of tags allow for duplicate values
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DeleteListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/OverwriteListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/OverwritePreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchListingByTagCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchPersonByTagCommandParser.java
Labels: type.Bug, priority.Medium

#260 Add tag allows for existing tag to be added if one of the new tag does not exist
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
Labels: type.Bug, priority.Medium

#317 Rename person list UI label from Clients to Persons
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Task, priority.Medium

#319 Fix exception for lower bound price bigger than upper bound price
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPreferenceCommandParser.java
Labels: type.Bug, severity.Low
