Repository AY2425S2-CS2103-F08-3/tp, pull requests merged in 2025-04, with the labels that each got.

#255 Update UG to reflect new commands
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Task, priority.Medium

#321 Update model CD for enumerations
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/style.puml
Labels: type.Task, priority.High

#329 Add defensive programming behaviour for invalid storage data
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/JsonAdaptedPriceRange.java
Labels: type.Task, priority.High

#323 Update use cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#327 Update sequence diagrams in DG
  docs/diagrams/EditListingSequenceDiagram.puml
  docs/diagrams/EditTagSequenceDiagram.puml
  docs/diagrams/MergeTagSequenceDiagram.puml
Labels: type.Task, priority.Medium

#335 Add non null checks for models
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/model/price/PriceRange.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Task, priority.Medium

#331 Update model CD for search context
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#340 Improve code quality
  src/main/java/seedu/address/commons/util/CommandUtil.java
  src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/DeleteListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteOwnerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/MatchPreferenceCommandParser.java
  src/main/java/seedu/address/logic/parser/OverwriteListingTagCommandParser.java
  src/main/java/seedu/address/logic/parser/OverwritePreferenceTagCommandParser.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/price/PriceRange.java
  src/main/java/seedu/address/model/search/comparators/ListingPreferenceScoreComparator.java
  src/main/java/seedu/address/model/search/comparators/PersonListingScoreComparator.java
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/java/seedu/address/ui/ListingListPanel.java
  src/main/java/seedu/address/ui/OwnerListPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/PreferenceListPanel.java
Labels: type.Task, priority.High

#338 Add non null checks for logic
  src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
  src/main/java/seedu/address/logic/commands/AddOwnerCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
  src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
  src/main/java/seedu/address/logic/commands/MatchListingCommand.java
  src/main/java/seedu/address/logic/commands/MatchPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/SearchListingByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchOwnerListingCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByName.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
Labels: type.Task, priority.Medium

#342 Add exclusive or null check for house number and unit number
  src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/test/java/seedu/address/logic/commands/DeleteListingTagCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchListingByTagCommandTest.java
  src/test/java/seedu/address/model/listing/predicates/ListingContainsAllTagsPredicateTest.java
Labels: type.Task, priority.Medium

#346 Standardize javaDocs for model component
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/listing/HouseNumber.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/listing/PostalCode.java
  src/main/java/seedu/address/model/listing/PropertyName.java
  src/main/java/seedu/address/model/listing/UniqueListingList.java
  src/main/java/seedu/address/model/listing/UnitNumber.java
  src/main/java/seedu/address/model/listing/exceptions/DuplicateListingException.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/model/price/PriceRange.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagMap.java
  src/main/java/seedu/address/model/tag/exceptions/DuplicateTagException.java
Labels: type.Task, priority.Medium

#349 Shift logic in searchPersonByNameCommand to parser
  src/main/java/seedu/address/logic/commands/SearchPersonByName.java
  src/main/java/seedu/address/logic/parser/SearchPersonByNameParser.java
  src/test/java/seedu/address/logic/commands/SearchPersonByNameTest.java
  src/test/java/seedu/address/logic/parser/SearchPersonByNameParserTest.java
Labels: type.Task, priority.Medium

#350 Fix use cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#356 Fix developer guide formatting
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#354 Add toString methods to commands
  src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
  src/main/java/seedu/address/logic/commands/AddOwnerCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
  src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
  src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchListingByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/listing/Listing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PropertyPreference.java
  src/main/java/seedu/address/model/price/Price.java
  src/main/java/seedu/address/model/price/PriceRange.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task, priority.Medium

#361 Update glossary in developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#352 Rename SearchPersonByName to SearchPersonByNameCommand
  src/main/java/seedu/address/logic/commands/SearchPersonByNameCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchPersonByNameCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/SearchPersonByNameCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchPersonByNameCommandParserTest.java
Labels: type.Task, priority.Medium

#364 Update DG with MergeTagSequenceDiagram
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#368 Update quick start in user guide
  docs/UserGuide.md
Labels: type.Task, priority.High

#370 Update general commands in user guide
  docs/UserGuide.md
Labels: type.Task, priority.High

#374 Rename clear command success message
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: type.Task, priority.High

#375 Modifying listing may shift it in the UI
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/search/comparators/DefaultListingComparator.java
Labels: type.Bug, severity.VeryLow, alpha-bug

#360 Further improve code quality
  src/main/java/seedu/address/commons/util/CommandUtil.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
  src/main/java/seedu/address/logic/commands/AddOwnerCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
  src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
  src/main/java/seedu/address/logic/commands/MatchListingCommand.java
  src/main/java/seedu/address/logic/commands/MatchPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchOwnerListingCommand.java
Labels: type.Task, priority.Medium

#380 Update unit number regex
  src/main/java/seedu/address/model/listing/UnitNumber.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: type.Task, priority.Medium

#384 Update glossary in developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#377 Update command usage message with UG message usage
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
  src/main/java/seedu/address/logic/commands/AddOwnerCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListListingCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/logic/commands/ListTagCommand.java
  src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
  src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
  src/main/java/seedu/address/logic/commands/MatchListingCommand.java
  src/main/java/seedu/address/logic/commands/MatchPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
  src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchListingByTagCommand.java
  src/main/java/seedu/address/logic/commands/SearchOwnerListingCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByNameCommand.java
  src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SearchPersonByNameCommandParser.java
  src/test/java/seedu/address/logic/parser/SearchPersonByNameCommandParserTest.java
Labels: type.Task, priority.Medium

#389 Improve code quality for search models
  src/main/java/seedu/address/model/search/comparators/DefaultListingComparator.java
  src/main/java/seedu/address/model/search/comparators/ListingPreferenceScoreComparator.java
  src/main/java/seedu/address/model/search/comparators/PersonListingScoreComparator.java
  src/main/java/seedu/address/model/search/predicates/ListingMatchesPreferencePredicate.java
  src/main/java/seedu/address/model/search/predicates/PersonMatchesPropertyPredicate.java
Labels: type.Task, priority.Medium

#385 Update sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task, priority.Medium

#397 Fix person sorting
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/search/comparators/DefaultPersonComparator.java
Labels: type.Bug, severity.Low

#382 Update user guide
  docs/UserGuide.md
  docs/images/CS2103UG/addListingAfter.png
  docs/images/CS2103UG/addListingBefore.png
  docs/images/CS2103UG/addListingTagAfter.png
  docs/images/CS2103UG/addListingTagBefore.png
  docs/images/CS2103UG/addOwnerAfter.png
  docs/images/CS2103UG/addOwnerBefore.png
  docs/images/CS2103UG/addPersonAfter.png
  docs/images/CS2103UG/addPersonBefore.png
  docs/images/CS2103UG/addPreferenceAfter.png
  docs/images/CS2103UG/addPreferenceBefore.png
  docs/images/CS2103UG/addPreferenceTagAfter.png
  docs/images/CS2103UG/addPreferenceTagBefore.png
  docs/images/CS2103UG/addTagAfter.png
  docs/images/CS2103UG/addTagBefore.png
  docs/images/CS2103UG/clearAfter.png
  docs/images/CS2103UG/clearBefore.png
  docs/images/CS2103UG/deleteListingAfter.png
  docs/images/CS2103UG/deleteListingBefore.png
  docs/images/CS2103UG/deleteListingTagAfter.png
  docs/images/CS2103UG/deleteListingTagBefore.png
  docs/images/CS2103UG/deleteOwnerAfter.png
  docs/images/CS2103UG/deleteOwnerBefore.png
  docs/images/CS2103UG/deletePersonAfter.png
  docs/images/CS2103UG/deletePersonBefore.png
  docs/images/CS2103UG/deletePreferenceAfter.png
  docs/images/CS2103UG/deletePreferenceBefore.png
  docs/images/CS2103UG/deletePreferenceTagAfter.png
  docs/images/CS2103UG/deletePreferenceTagBefore.png
  docs/images/CS2103UG/deleteTagAfter.png
  docs/images/CS2103UG/deleteTagBefore.png
  docs/images/CS2103UG/editPersonAfter.png
  docs/images/CS2103UG/editPersonBefore.png
  docs/images/CS2103UG/listListingAfter.png
  docs/images/CS2103UG/listListingBefore.png
  docs/images/CS2103UG/listPersonAfter.png
  docs/images/CS2103UG/listPersonBefore.png
  docs/images/CS2103UG/listTagAfter.png
  docs/images/CS2103UG/listTagBefore.png
  docs/images/CS2103UG/markAvailableAfter.png
  docs/images/CS2103UG/markAvailableBefore.png
  docs/images/CS2103UG/markBefore.png
  docs/images/CS2103UG/markUnavailableAfter.png
  docs/images/CS2103UG/matchListingAfter.png
  docs/images/CS2103UG/matchListingBefore.png
  docs/images/CS2103UG/matchPreferenceAfter.png
  docs/images/CS2103UG/matchPreferenceBefore.png
  docs/images/CS2103UG/overwriteListingTagAfter.png
  docs/images/CS2103UG/overwriteListingTagBefore.png
  docs/images/CS2103UG/overwritePreferenceTagAfter.png
  docs/images/CS2103UG/overwritePreferenceTagBefore.png
  docs/images/CS2103UG/searchListingTagAfter.png
  docs/images/CS2103UG/searchListingTagBefore.png
  docs/images/CS2103UG/searchOwnerListingAfter.png
  docs/images/CS2103UG/searchOwnerListingBefore.png
  docs/images/CS2103UG/searchPersonNameAfter.png
  docs/images/CS2103UG/searchPersonNameBefore.png
  docs/images/CS2103UG/searchPersonTagAfter.png
  docs/images/CS2103UG/searchPersonTagBefore.png
Labels: type.Task, priority.High

#400 Update house number regex validation
  src/main/java/seedu/address/model/listing/HouseNumber.java
Labels: type.Task, priority.Medium

#398 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: type.Task, priority.High

#403 Update listing use cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#404 Update input restrictions in UG
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/CS2103UG/matchEstate.png
  docs/images/CS2103UG/sampleData.png
  docs/index.md
Labels: type.Task, priority.Medium

#471 Fix UG bugs
  docs/UserGuide.md
Labels: type.Bug

#466 Fix Price Range collapsing in UI
  src/main/java/seedu/address/ui/ListingCard.java
  src/main/java/seedu/address/ui/PreferenceCard.java
Labels: type.Bug, severity.Low

#474 Add consideration section to DG
  docs/DeveloperGuide.md
Labels: type.Task

#475 Update UG application brief description
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
  src/main/java/seedu/address/model/person/Email.java
Labels: type.Bug, priority.Medium

#479 Fix use case extension repetition in developer guide
  docs/DeveloperGuide.md
Labels: type.Bug, severity.VeryLow

#481 add editPreferenceSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/EditPreferenceSequenceDiagram.puml
Labels: type.Task, priority.Medium

#483 Fix tag list scroll when many tags
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TagListPanel.fxml
Labels: type.Bug, severity.High

#485 Add tag filtering consideration in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#470 Add more example commands to user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#487 Update UG image for help command
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Bug, severity.VeryLow

#490 Update UG jar name
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#492 Add author to UG sections
  docs/UserGuide.md
Labels: type.Task, priority.Medium
